language: python

services:
  - docker

install:
  - pip install -r src/requirements.txt

script:
  - pytest

deploy:
  provider: script
  script: bash docker_push $TRAVIS_BUILD_NUMBER
  on:
    branch: master
