dist: xenial
language: minimal

services:
  - docker

before_install:
  - bash docker_build

script:
  - docker run --rm $IMAGE pytest

deploy:
  provider: script
  script: bash docker_deploy
  on:
    branch: master

notifications:
  webhooks: $NOTIFY_URL
